sudo: required
language: node_js
node_js:
  - "13"
services:
  - docker

install:
  - npm install

script:
  - npm test

deploy:
  skip_cleanup: true
  provider: heroku
  api_key: $API_KEY
  app: fis-backend-login