sudo: required
language: node_js
node_js:
  - "13"
services:
  - docker

install:
  - npm install

script:
  - npm test

env:
  - secret=$secret
  - uriDataBase=$uriDataBase
  - urlApp=$urlApp

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $API_KEY
  app: fis-backend-login