@startuml
title checkToken
boundary API_Gateway
control UserRouter
control Middleware
activate API_Gateway
API_Gateway -> UserRouter : getUser(token,login)
activate UserRouter
UserRouter -> Middleware : withAuth(token)
activate Middleware
alt !token
    Middleware -> UserRouter : 'Unauthorized: No token provided (401)'
    UserRouter -> API_Gateway : 'Unauthorized: No token provided (401)'
else 
    Middleware -> Middleware : jwt.verify(token)
    alt token != valid
        Middleware -> UserRouter : 'Unauthorized: Invalid token (401)'
        UserRouter -> API_Gateway : 'Unauthorized: Invalid token (401)'
    else
        Middleware -> UserRouter : Token Valid
        deactivate Middleware
        UserRouter -> API_Gateway : return(res.sendStatus(200))
        deactivate UserRouter
        deactivate API_Gateway
    end
end
@enduml