@startuml
title Forgotten Password
boundary API_Gateway
control UserRouter
control UserController
dataBase UserDB
control Outlook
activate API_Gateway
API_Gateway -> UserRouter : forgottenPassword(email)
activate UserRouter
UserRouter -> UserController : forgottenPassword(email)
activate UserController
alt (!email)
    UserController -> UserRouter : 'You must provide an email (400)'
    UserRouter -> API_Gateway : 'You must provide an email (400)'
else
    UserController -> UserDB : findOne(user)
    activate UserDB
    UserDB -> UserController : userFind
    deactivate UserDB
    alt !userFind
        UserController -> UserRouter : 'Email not found!(404)'
        UserRouter -> API_Gateway : 'Email not found!(404)'
    else
        UserController -> Outlook : sendMail(token)
        activate Outlook
        Outlook -> UserController : emailSend
        deactivate Outlook
        alt !emailSend
            UserController -> UserRouter : return(res.status(500))
            UserRouter -> API_Gateway : return(res.status(500))
        else
            UserController -> UserRouter : return(res.status(200))
            UserRouter -> API_Gateway : return(res.status(200))
        end
    end
    deactivate UserController
    deactivate UserRouter
end
deactivate API_Gateway
@enduml
