@startuml
title User getUser
boundary API_Gateway
control UserRouter
control Middleware
control UserController
dataBase UserDB
activate API_Gateway
API_Gateway -> UserRouter : getUser(token)
activate UserRouter
UserRouter -> Middleware : withAuth(token)
activate Middleware
alt !token
    Middleware -> UserRouter : 'Unauthorized: No token provided (401)'
    UserRouter -> API_Gateway : 'Unauthorized: No token provided (401)'
else 
    Middleware -> Middleware : jwt.verify(token)
    alt token != valid
        Middleware -> UserRouter : 'Unauthorized: Invalid token (401)'
        UserRouter -> API_Gateway : 'Unauthorized: Invalid token (401)'
    else
        Middleware -> UserRouter : Token Valid
        deactivate Middleware
        UserRouter -> UserController : getUser(login)
        activate UserController
        UserController -> UserDB : find(login)
        activate UserDB
        UserDB -> UserController : userFind
        deactivate UserDB
        alt userFind == null
            UserController -> UserRouter : 'User not found (404)'
        UserRouter -> API_Gateway : 'User not found (404)'
        else
            UserController -> UserRouter : return(res.status(200), userFind)
            UserRouter -> API_Gateway : return(res.status(200), userFind)
        end
        deactivate UserController
        deactivate UserRouter
        deactivate API_Gateway
    end
end
@enduml